cscript.exe %current%Fonts\install.vbs GDCOBL__.TTF %current%Fonts       
cscript.exe %current%Fonts\install.vbs GDCORP__.TTF %current%Fonts
cscript.exe %current%Fonts\install.vbs GDLIM___.TTF %current%Fonts      
cscript.exe %current%Fonts\install.vbs GDPROP__.TTF %current%Fonts   
cscript.exe %current%Fonts\install.vbs GDUNIV__.TTF %current%Fonts   
cscript.exe %current%Fonts\install.vbs GDUNL___.TTF %current%Fonts
cscript.exe %current%Fonts\install.vbs HELVBLAK.TTF %current%Fonts   
cscript.exe %current%Fonts\install.vbs HELVCOND.TTF %current%Fonts   
cscript.exe %current%Fonts\install.vbs HELVET10.TTF %current%Fonts 
cscript.exe %current%Fonts\install.vbs HELVET11.TTF %current%Fonts     
cscript.exe %current%Fonts\install.vbs HELVET12.TTF %current%Fonts            
cscript.exe %current%Fonts\install.vbs HELVET13.TTF %current%Fonts     
cscript.exe %current%Fonts\install.vbs HELVET14.TTF %current%Fonts     
cscript.exe %current%Fonts\install.vbs HELVET15.TTF %current%Fonts     
cscript.exe %current%Fonts\install.vbs HELVET16.TTF %current%Fonts     
cscript.exe %current%Fonts\install.vbs HELVET17.TTF %current%Fonts     
cscript.exe %current%Fonts\install.vbs HELVETI1.TTF %current%Fonts     
cscript.exe %current%Fonts\install.vbs HELVETI2.TTF %current%Fonts     
cscript.exe %current%Fonts\install.vbs HELVETI3.TTF %current%Fonts     
cscript.exe %current%Fonts\install.vbs HELVETI4.TTF %current%Fonts     
cscript.exe %current%Fonts\install.vbs HELVETI5.TTF %current%Fonts     
cscript.exe %current%Fonts\install.vbs HELVETI6.TTF %current%Fonts     
cscript.exe %current%Fonts\install.vbs HELVETI7.TTF %current%Fonts     
cscript.exe %current%Fonts\install.vbs HELVETI8.TTF %current%Fonts     
cscript.exe %current%Fonts\install.vbs HELVETI9.TTF %current%Fonts     
cscript.exe %current%Fonts\install.vbs HELVETIC.TTF %current%Fonts     
cscript.exe %current%Fonts\install.vbs SKANDARW.TTF %current%Fonts     
cscript.exe %current%Fonts\install.vbs SKANDATA.TTF %current%Fonts     
cscript.exe %current%Fonts\install.vbs SKANDATR.TTF %current%Fonts     
cscript.exe %current%Fonts\install.vbs SKANDATW.TTF %current%Fonts     
cscript.exe %current%Fonts\install.vbs UNIVBLO_.TTF %current%Fonts     
cscript.exe %current%Fonts\install.vbs UNIVBL__.TTF %current%Fonts     
cscript.exe %current%Fonts\install.vbs UNIVBO__.TTF %current%Fonts            
cscript.exe %current%Fonts\install.vbs UNIVB___.TTF %current%Fonts            
cscript.exe %current%Fonts\install.vbs UNIVERS_.TTF %current%Fonts            
cscript.exe %current%Fonts\install.vbs UNIVLO__.TTF %current%Fonts     
cscript.exe %current%Fonts\install.vbs Univlto__.ttf %current%Fonts            
cscript.exe %current%Fonts\install.vbs UNIVLT__.TTF %current%Fonts            
cscript.exe %current%Fonts\install.vbs UNIVL___.TTF %current%Fonts     
cscript.exe %current%Fonts\install.vbs UNIVO___.TTF %current%Fonts     
cscript.exe %current%Fonts\install.vbs UNVBBLO_.TTF %current%Fonts     
  
